apiVersion: v1
kind: Secret
metadata:
  name: {{ include "faraway-edge.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "faraway-edge.labels" . | nindent 4 }}
type: Opaque
data:
  config.json: {{ .Values.config | toJson | b64enc | quote }}
